/** Etiquetas funcionales del contacto; orden en/he/ru/ar. */
const labels = {
  comparison: ['Compare before saving','השוואה לפני שמירה','Сравнение перед сохранением','المقارنة قبل الحفظ'],
  field: ['Field','שדה','Поле','الحقل'],
  current: ['Current record','הרשומה הנוכחית','Текущая запись','السجل الحالي'],
  draft: ['Your draft','הטיוטה שלך','Ваш черновик','مسودتك'],
  adopt: ['Keep my edited fields on this version','שמירת השדות שערכתי על גרסה זו','Сохранить мои правки на этой версии','الاحتفاظ بتعديلاتي على هذه النسخة'],
  addTag: ['Add tag','הוספת תגית','Добавить метку','إضافة وسم'],
  removeTag: ['Remove tag','הסרת תגית','Удалить метку','إزالة الوسم'],
  legacy: ['Historical values','ערכים היסטוריים','Исторические значения','القيم التاريخية'],
  legacyLimit: ['Original contact values; units and attendance are unverified. These are not confirmed payments or visits.','ערכי קשר מקוריים; היחידות והנוכחות לא אומתו. אין אלה תשלומים או ביקורים מאושרים.','Исходные значения контакта; единицы и посещения не подтверждены. Это не подтверждённые платежи или визиты.','قيم جهة الاتصال الأصلية؛ الوحدات والحضور غير موثقين. لا تمثل مدفوعات أو زيارات مؤكدة.'],
  lifetimeValueCents: ['Historical total value','ערך כולל היסטורי','Историческая общая сумма','القيمة الإجمالية التاريخية'],
  amountPaidCents: ['Historical paid value','ערך ששולם היסטורית','Историческая сумма оплаты','قيمة الدفع التاريخية'],
  visitCount: ['Historical visit count','מספר ביקורים היסטורי','Историческое число посещений','عدد الزيارات التاريخي'],
  lastServiceId: ['Historical service reference','מזהה שירות היסטורי','Историческая ссылка на услугу','مرجع الخدمة التاريخي'],
  paymentMethod: ['Historical payment method','אמצעי תשלום היסטורי','Исторический способ оплаты','طريقة الدفع التاريخية'],
  lastVisitAt: ['Historical last visit','ביקור אחרון היסטורי','Историческое последнее посещение','آخر زيارة تاريخية'],
  lastContactedAt: ['Last recorded contact','יצירת קשר אחרונה שתועדה','Последний записанный контакт','آخر تواصل مسجل'],
  enabled: ['Allowed','מורשה','Разрешено','مسموح'],
  disabled: ['Not allowed','לא מורשה','Не разрешено','غير مسموح'],
  createCapacity: ['Create minimal contacts','יצירת אנשי קשר בסיסיים','Создание минимальных контактов','إنشاء جهات اتصال أساسية'],
  allowCreate: ['Allow contact creation','הרשאת יצירת קשר','Разрешить создание контактов','السماح بإنشاء جهات اتصال'],
  denyCreate: ['Revoke contact creation','ביטול הרשאת יצירת קשר','Отозвать создание контактов','سحب إذن إنشاء جهات اتصال'],
  noStaff: ['No active staff members','אין אנשי צוות פעילים','Нет активных сотрудников','لا يوجد موظفون نشطون'],
  refreshAccess: ['Refresh access','רענון הרשאות','Обновить доступ','تحديث الوصول'],
  archiveFilter: ['Contact state','מצב איש קשר','Состояние контакта','حالة جهة الاتصال'],
  activeContacts: ['Active contacts','אנשי קשר פעילים','Активные контакты','جهات الاتصال النشطة'],
  archivedContacts: ['Archived contacts','אנשי קשר בארכיון','Архивные контакты','جهات الاتصال المؤرشفة'],
  allContacts: ['All permitted contacts','כל אנשי הקשר המורשים','Все доступные контакты','جميع جهات الاتصال المسموح بها'],
  title: ['Contact details','פרטי איש קשר','Данные контакта','تفاصيل جهة الاتصال'],
  name: ['Name','שם','Имя','الاسم'],
  email: ['Email (optional)','דוא״ל (לא חובה)','Email (необязательно)','البريد الإلكتروني (اختياري)'],
  phone: ['Phone (optional)','טלפון (לא חובה)','Телефон (необязательно)','الهاتف (اختياري)'],
  channel: ['Contact source','מקור הקשר','Источник контакта','مصدر التواصل'],
  tags: ['Tags','תגיות','Метки','الوسوم'],
  stage: ['Stage','שלב','Этап','المرحلة'],
  none: ['Not recorded','לא תועד','Не указано','غير مسجل'],
  notes: ['Private notes','הערות פרטיות','Личные заметки','ملاحظات خاصة'],
  save: ['Save changes','שמירת שינויים','Сохранить изменения','حفظ التغييرات'],
  saving: ['Saving…','שומר…','Сохранение…','جارٍ الحفظ…'],
  saved: ['Changes confirmed','השינויים אושרו','Изменения подтверждены','تم تأكيد التغييرات'],
  failed: ['Could not confirm. Your draft is retained.','לא ניתן לאשר. הטיוטה נשמרה.','Не удалось подтвердить. Черновик сохранён.','تعذر التأكيد. تم الاحتفاظ بالمسودة.'],
  conflict: ['The record changed. Review the current version before submitting again.','הרשומה השתנתה. יש לבדוק את הגרסה הנוכחית לפני שליחה נוספת.','Запись изменилась. Проверьте текущую версию перед повторной отправкой.','تغير السجل. راجع النسخة الحالية قبل الإرسال مجدداً.'],
  uncertain: ['Result unknown. Check this operation before making another change.','התוצאה לא ידועה. יש לבדוק את הפעולה לפני שינוי נוסף.','Результат неизвестен. Проверьте операцию перед новым изменением.','النتيجة غير معروفة. تحقق من العملية قبل إجراء تغيير آخر.'],
  recover: ['Check operation','בדיקת הפעולה','Проверить операцию','التحقق من العملية'],
  retry: ['Retry same operation','ניסיון חוזר של אותה פעולה','Повторить ту же операцию','إعادة محاولة العملية نفسها'],
  reload: ['Review current version','בדיקת הגרסה הנוכחית','Проверить текущую версию','مراجعة النسخة الحالية'],
  reason: ['Reason','סיבה','Причина','السبب'],
  archive: ['Archive contact','ארכוב איש הקשר','Архивировать контакт','أرشفة جهة الاتصال'],
  restore: ['Restore contact','שחזור איש הקשר','Восстановить контакт','استعادة جهة الاتصال'],
  archived: ['Archived — existing records are retained','בארכיון — הרשומות הקיימות נשמרו','В архиве — существующие записи сохранены','مؤرشف — السجلات الحالية محفوظة'],
  access: ['Direct access','גישה ישירה','Прямой доступ','الوصول المباشر'],
  member: ['Staff member','איש צוות','Сотрудник','الموظف'],
  allow: ['Allow reading','הרשאת קריאה','Разрешить чтение','السماح بالقراءة'],
  revoke: ['Revoke reading','ביטול הרשאת קריאה','Отозвать чтение','سحب إذن القراءة'],
  history: ['Contact change history','היסטוריית שינויי איש הקשר','История изменений контакта','سجل تغييرات جهة الاتصال'],
  more: ['Load more','טעינת עוד','Загрузить ещё','تحميل المزيد'],
  empty: ['No changes recorded','לא תועדו שינויים','Изменений нет','لا توجد تغييرات مسجلة'],
  close: ['Close','סגירה','Закрыть','إغلاق'],
  visitsUnknown: ['Attendance is not verified by this contact record.','הנוכחות לא אומתה ברשומת איש קשר זו.','Посещения не подтверждены этой записью контакта.','هذا السجل لا يثبت الحضور.'],
  manual: ['Manual','ידני','Вручную','يدوي'],
  web: ['Website','אתר','Сайт','الموقع'],
  walkin: ['In person','במקום','Лично','حضوري'],
  booking: ['Booking','הזמנה','Бронирование','حجز'],
  import: ['Import','ייבוא','Импорт','استيراد'],
  whatsapp: ['WhatsApp','WhatsApp','WhatsApp','WhatsApp'],
  instagram: ['Instagram','Instagram','Instagram','Instagram'],
  google: ['Google','Google','Google','Google'],
  referral: ['Referral','הפניה','Рекомендация','إحالة'],
  lead: ['New contact','איש קשר חדש','Новый контакт','جهة اتصال جديدة'],
  contacted: ['Contacted','נוצר קשר','Связались','تم التواصل'],
  scheduled: ['Scheduled','נקבע מועד','Запланировано','مجدول'],
  converted: ['Converted','הפך ללקוח','Стал клиентом','أصبح عميلاً'],
  lost: ['Closed','נסגר','Закрыт','مغلق'],
  create: ['Contact created','איש קשר נוצר','Контакт создан','تم إنشاء جهة الاتصال'],
  update: ['Contact edited','איש קשר נערך','Контакт изменён','تم تعديل جهة الاتصال'],
  grant: ['Reading granted','ניתנה הרשאת קריאה','Чтение разрешено','تم منح القراءة'],
} as const;
export function contactText(language: string, key: keyof typeof labels): string {
  return labels[key][language === 'he' ? 1 : language === 'ru' ? 2 : language === 'ar' ? 3 : 0];
}
