/** Textos funcionales del mismo REG en los cuatro idiomas ofrecidos. */
const labels={
  refundCorrections:['Dependent refund corrections','תיקוני החזרים תלויים','تصحيحات الاسترداد التابعة','Исправления связанных возвратов'],
  includeCorrection:['Include in this correction','לכלול בתיקון זה','تضمين في هذا التصحيح','Включить в это исправление'],
  explicitUnit:['Enter each amount in the selected currency. No automatic conversion; all changes commit together.','יש להזין כל סכום במטבע הנבחר. אין המרה אוטומטית; כל השינויים נשמרים יחד.','أدخل كل مبلغ بالعملة المحددة. لا تحويل تلقائي؛ تحفظ التغييرات معاً.','Введите каждую сумму в выбранной валюте. Автоконвертации нет; изменения сохраняются вместе.'],
  scale:['Decimal places','ספרות עשרוניות','المنازل العشرية','Десятичных знаков'],
  historyIncomplete:['Historical source unavailable; retained rows are incomplete','מקור היסטורי לא זמין; הרשומות השמורות אינן מלאות','المصدر التاريخي غير متاح؛ السجلات المحفوظة غير مكتملة','Источник истории недоступен; сохранённые записи неполны'],
  period:['Monetary period','תקופה כספית','الفترة المالية','Денежный период'],
  days7:['Last 7 days','7 ימים אחרונים','آخر 7 أيام','Последние 7 дней'],
  days30:['Last 30 days','30 ימים אחרונים','آخر 30 يوماً','Последние 30 дней'],
  custom:['Custom period','תקופה מותאמת','فترة مخصصة','Выбрать период'],
  allDates:['All dates','כל התאריכים','كل التواريخ','Все даты'],
  from:['From','מתאריך','من','С'],
  to:['To','עד תאריך','إلى','По'],
  invalidPeriod:['Choose valid dates in order','יש לבחור תאריכים תקינים לפי הסדר','اختر تواريخ صحيحة بالترتيب','Укажите корректные даты по порядку'],
  periodBasis:['Receipt/refund effective date; undated records stay visible as unknown','לפי מועד התקבול או ההחזר; רשומות ללא תאריך מוצגות כלא ידועות','حسب تاريخ القبض أو الاسترداد؛ السجلات بلا تاريخ تبقى ظاهرة كغير معروفة','По дате поступления/возврата; записи без даты видны как неизвестные'],
  customer:['Customer','לקוח','العميل','Клиент'],
  service:['Service','שירות','الخدمة','Услуга'],
  professional:['Professional','איש צוות','المختص','Специалист'],
  recordedContext:['Stored in the original record','שמור ברשומה המקורית','محفوظ في السجل الأصلي','Сохранено в исходной записи'],
  currentContext:['Current catalogue reference; historical name unconfirmed','הפניה למחירון הנוכחי; השם ההיסטורי לא אומת','مرجع الكتالوج الحالي؛ الاسم التاريخي غير مؤكد','Текущий справочник; историческое название не подтверждено'],
  appointmentDate:['Appointment date; not a confirmed money date','תאריך תור; אינו תאריך כספי מאומת','تاريخ الموعد؛ ليس تاريخاً مالياً مؤكداً','Дата записи; не подтверждённая дата денег'],
  originalFields:['Original fields','שדות מקוריים','الحقول الأصلية','Исходные поля'],
  legacyPeriod:['Unlinked history is outside period totals; its monetary date is unconfirmed','ההיסטוריה הלא מקושרת מחוץ לסיכומי התקופה; מועד הכסף אינו מאומת','السجل غير المرتبط خارج إجماليات الفترة؛ تاريخه المالي غير مؤكد','Несвязанная история вне итогов периода; дата денег не подтверждена'],
  allAgreements:['Agreements: current state across all dates','הסכמות: מצב נוכחי בכל התאריכים','الاتفاقات: الحالة الحالية لكل التواريخ','Договорённости: текущее состояние за всё время'],
  ownScope:['Own records','רשומות שלי','سجلاتي','Свои записи'],
  allScope:['All business records','כל רשומות העסק','كل سجلات النشاط','Все записи бизнеса'],
  revoked:['Revoked','בוטל','ملغى','Отозвано'],
  newAttempt:['Edit and start a new attempt','עריכה והתחלת ניסיון חדש','تعديل وبدء محاولة جديدة','Изменить и начать новую попытку'],
  partial:['Partial coverage; not a complete balance','כיסוי חלקי; אינו יתרה מלאה','تغطية جزئية؛ ليست رصيداً كاملاً','Неполное покрытие; это не полный баланс'],
  estimate:['Estimate at current catalogue prices','אומדן לפי המחירון הנוכחי','تقدير بأسعار الكتالوج الحالية','Оценка по текущему прайс-листу'],
  unlinked:['Unlinked history; currency or scale may be unknown','היסטוריה ללא קישור; מטבע או יחידה עשויים להיות לא ידועים','سجل غير مرتبط؛ قد تكون العملة أو الوحدة غير معروفة','Несвязанная история; валюта или масштаб могут быть неизвестны'],
  title:['Money register','רישום כספים','سجل الأموال','Денежный реестр'],
  declaration:['Operator declarations; no bank confirmation','הצהרות העסק; ללא אישור בנקאי','تصريحات النشاط؛ دون تأكيد بنكي','Заявления бизнеса; без банковского подтверждения'],
  received:['Declared receipts','תקבולים מוצהרים','مقبوضات معلنة','Заявленные поступления'],
  refunded:['Declared refunds','החזרים מוצהרים','مبالغ مستردة معلنة','Заявленные возвраты'],
  net:['Net declared amount','סכום מוצהר נטו','صافي المبلغ المعلن','Чистая заявленная сумма'],
  unknown:['Unknown','לא ידוע','غير معروف','Неизвестно'],
  pending:['Pending','ממתין','قيد الانتظار','Ожидается'],
  pending_normalization:['Pending normalization','ממתין להשלמת נתונים','بانتظار استكمال البيانات','Ожидает уточнения данных'],
  received_declared:['Received — declared','התקבל — מוצהר','مستلم — معلن','Получено — заявлено'],
  refund_pending:['Refund pending','החזר ממתין','استرداد معلق','Возврат ожидается'],
  refund_declared:['Refunded — declared','הוחזר — מוצהר','مسترد — معلن','Возвращено — заявлено'],
  rejected:['Rejected','נדחה','مرفوض','Отклонено'],
  void:['Voided declaration','הצהרה מבוטלת','تصريح ملغى','Заявление аннулировано'],
  review:['Needs review','דורש בדיקה','يحتاج مراجعة','Требует проверки'],
  receipt:['Receipt','תקבול','قبض','Поступление'],
  refund:['Refund','החזר','استرداد','Возврат'],
  create:['New receipt','תקבול חדש','قبض جديد','Новое поступление'],
  correct:['Correct declaration','תיקון הצהרה','تصحيح التصريح','Исправить заявление'],
  save:['Confirm declaration','אישור ההצהרה','تأكيد التصريح','Подтвердить заявление'],
  cancel:['Cancel this form','ביטול הטופס','إلغاء النموذج','Закрыть форму'],
  amount:['Amount','סכום','المبلغ','Сумма'],
  currency:['Currency','מטבע','العملة','Валюта'],
  method:['Payment method','אמצעי תשלום','طريقة الدفع','Способ оплаты'],
  methods:['Manage methods','ניהול אמצעי תשלום','إدارة طرق الدفع','Способы оплаты'],
  enabled:['Enabled','פעיל','مفعل','Включён'],
  suspended:['Suspended','מושהה','موقوف','Приостановлен'],
  label:['Name','שם','الاسم','Название'],
  date:['Effective local date and time','תאריך ושעה מקומיים בפועל','التاريخ والوقت المحلي الفعلي','Фактические местные дата и время'],
  offset:['Confirm UTC offset','אישור היסט UTC','تأكيد فرق UTC','Подтвердите смещение UTC'],
  state:['State','מצב','الحالة','Состояние'],
  description:['Description','תיאור','الوصف','Описание'],
  reason:['Reason for correction','סיבת התיקון','سبب التصحيح','Причина исправления'],
  evidence:['Declared evidence','אסמכתה מוצהרת','دليل معلن','Заявленное основание'],
  reference:['Reference (optional)','אסמכתה (רשות)','مرجع (اختياري)','Ссылка (необязательно)'],
  noEvidence:['No attachment declared','לא הוצהר על קובץ מצורף','لم يصرح بمرفق','Вложение не заявлено'],
  raw:['Original unknown data','נתונים מקוריים לא מזוהים','البيانات الأصلية غير المعروفة','Исходные неуточнённые данные'],
  agreement:['Agreement','הסכם','اتفاق','Соглашение'],
  agreements:['Manage agreements','ניהול הסכמים','إدارة الاتفاقات','Соглашения'],
  total:['Agreed total (blank = unknown)','סכום מוסכם (ריק = לא ידוע)','الإجمالي المتفق عليه (فارغ = غير معروف)','Согласованная сумма (пусто = неизвестно)'],
  balance:['Pending balance','יתרה לתשלום','الرصيد المستحق','Остаток к оплате'],
  credit:['Credit','זכות','رصيد دائن','Переплата'],
  allocate:['Allocate money','שיוך כסף','تخصيص مبلغ','Распределить деньги'],
  active:['Active','פעיל','نشط','Активно'],
  released:['Released','שוחרר','محرر','Освобождено'],
  distribution:['Refund distribution (must equal refund)','חלוקת ההחזר (חייבת להתאים לסכום)','توزيع الاسترداد (يجب أن يساوي المبلغ)','Распределение возврата (должно равняться сумме)'],
  unallocated:['Unallocated portion','חלק לא משויך','جزء غير مخصص','Нераспределённая часть'],
  dependencies:['Related allocations after correction','שיוכים לאחר התיקון','التخصيصات بعد التصحيح','Распределения после исправления'],
  history:['History','היסטוריה','السجل','История'],
  author:['Author','מחבר','المسجل','Автор'],
  recorded:['Recorded at','נרשם בתאריך','وقت التسجيل','Время записи'],
  revision:['Revision','גרסה','المراجعة','Редакция'],
  reload:['Reload','טעינה מחדש','إعادة التحميل','Обновить'],
  export:['Export this cut','ייצוא תמונת המצב','تصدير هذه اللقطة','Экспорт этого среза'],
  empty:['No records','אין רשומות','لا توجد سجلات','Нет записей'],
  loading:['Loading','טוען','جار التحميل','Загрузка'],
  unavailable:['Register unavailable. Your data is preserved.','הרישום אינו זמין. הנתונים נשמרו.','السجل غير متاح. بياناتك محفوظة.','Реестр недоступен. Ваши данные сохранены.'],
  error:['Could not confirm. Review data, permission and current revision.','לא ניתן לאשר. בדקו נתונים, הרשאה וגרסה.','تعذر التأكيد. راجع البيانات والصلاحية والمراجعة.','Подтвердить не удалось. Проверьте данные, доступ и редакцию.'],
  uncertain:['Result uncertain; keep this attempt and check its status.','התוצאה אינה ודאית; שמרו את הניסיון ובדקו את מצבו.','النتيجة غير مؤكدة؛ احتفظ بالمحاولة وتحقق من حالتها.','Результат неизвестен; сохраните попытку и проверьте её статус.'],
  recover:['Check saved attempt','בדיקת ניסיון שמור','فحص المحاولة المحفوظة','Проверить сохранённую попытку'],
  retry:['Retry same attempt','ניסיון חוזר עם אותו מזהה','إعادة نفس المحاولة','Повторить ту же попытку'],
  accepted:['Declaration saved','ההצהרה נשמרה','تم حفظ التصريح','Заявление сохранено'],
  legacy:['Legacy history — excluded from REG totals','היסטוריה ישנה — מחוץ לסיכומי REG','السجل القديم — مستبعد من إجماليات REG','Прежние записи — вне итогов REG'],
  source:['Source','מקור','المصدر','Источник'],
  links:['Confirmed links','קישורים מאושרים','روابط مؤكدة','Подтверждённые связи'],
  noLink:['No appointment or contact required','אין צורך בתור או באיש קשר','لا يلزم موعد أو جهة اتصال','Запись или контакт не обязательны'],
  limit:['At most 50 related changes per command','עד 50 שינויים קשורים בפקודה','حتى 50 تغييرا مرتبطا لكل أمر','Не более 50 связанных изменений за действие'],
  readOnly:['Read only; new declarations are blocked','קריאה בלבד; הצהרות חדשות חסומות','للقراءة فقط؛ التصريحات الجديدة محظورة','Только чтение; новые заявления заблокированы'],
  reviewCount:['Correspondences pending review','התאמות הממתינות לבדיקה','مطابقات بانتظار المراجعة','Соответствия ожидают проверки'],
  exclude:['Excluded representations','ייצוגים שלא נספרים','تمثيلات مستبعدة','Исключённые представления'],
  evidenceManage:['Link declared evidence','קישור אסמכתה מוצהרת','ربط دليل معلن','Связать заявленное основание'],
  provider:['Declared provider','ספק מוצהר','مزود معلن','Заявленный провайдер'],
  account:['Declared account','חשבון מוצהר','حساب معلن','Заявленный счёт'],
  externalId:['External reference ID','מזהה אסמכתה חיצוני','معرف المرجع الخارجي','Идентификатор внешнего основания'],
  type:['Type','סוג','النوع','Тип'],
  cut:['Source cut','מועד חתך המקור','لقطة المصدر','Срез источника'],
  aggregate:['Aggregate closure (keep detail separately)','סגירה מצטברת (הפירוט נשמר בנפרד)','إقفال مجمع (التفاصيل تبقى منفصلة)','Сводное закрытие (детали сохраняются отдельно)'],
  related:['Related record IDs','מזהי רשומות קשורות','معرفات السجلات المرتبطة','Идентификаторы связанных записей'],
  grants:['Money permissions','הרשאות כספיות','صلاحيات الأموال','Доступ к денежным операциям'],
  email:['Member email','דוא״ל חבר צוות','بريد العضو','Почта участника'],
  uid:['Member user ID','מזהה משתמש של החבר','معرف مستخدم العضو','Идентификатор пользователя'],
  role:['Role','תפקיד','الدور','Роль'],
  scope:['Own / all records','רשומות אישיות / כולן','سجلات خاصة / جميع السجلات','Свои / все записи'],
  memberVersion:['Current membership version','גרסת חברות נוכחית','نسخة العضوية الحالية','Текущая версия членства'],
} satisfies Record<string,readonly [string,string,string,string]>;
export type RegLabel=keyof typeof labels;
export function regText(language:string,key:RegLabel):string{return labels[key][language==='he'?1:language==='ar'?2:language==='ru'?3:0];}
