import assert from 'node:assert/strict';
import type { Firestore } from 'firebase-admin/firestore';
import { executeCommand, commandStatus, readEvents } from '../src/lib/reg/store.js';
import { projectReg, agreementBalance } from '../src/lib/reg/projection.js';
import { membershipVersion, physicalId, principalId, type RegContext } from '../src/lib/reg/authority.js';
import { CAPABILITIES, type Actor, type Command, type Control, type Grant, type Operation, type Agreement, type Allocation } from '../src/lib/reg/types.js';

/** Recorridos monetarios en autoridad ficticia separada; cada rechazo comprueba ausencia de commits. */
export async function runDomainNative(db:Firestore,base:RegContext):Promise<void>{
  const ctx={...base,clientId:'tenant-domain'},actor:Actor={issuer:ctx.issuer,uid:'domain-owner',email:'domain-owner@example.invalid'};
  const now=ctx.now!(),member={clientId:ctx.clientId,role:'owner',status:'active',invitedAt:now};
  const control:Control={clientId:ctx.clientId,environment:ctx.environment,authorityId:ctx.authorityId,schemaVersion:1,epoch:1,dataRevision:0,mode:'ready',minClientVersion:1,currencies:{ILS:2,USD:2,JPY:0,KWD:3}};
  const grant:Grant={purpose:"merchant_customer_money",id:principalId(actor),clientId:ctx.clientId,environment:ctx.environment,schemaVersion:1,revision:1,authoredBy:actor,recordedAt:now,...actor,role:'owner',state:'active',scope:'all',capabilities:[...CAPABILITIES],membershipVersion:membershipVersion(member),epoch:1};
  await db.collection('admin_users').doc(actor.email).set(member);
  await db.collection('reg_legacy_fence').doc(ctx.clientId).set({authorityId:ctx.authorityId,environment:ctx.environment,epoch:1,manualMoney:'blocked'});
  await db.collection('reg_control').doc(physicalId(ctx,'control')).set(control);
  await db.collection('reg_grants').doc(physicalId(ctx,grant.id)).set(grant);
  let sequence=0;
  const amount=(amountMinor:string,currency='ILS')=>({amountMinor,currency,scale:control.currencies[currency]});
  const date={instant:'2026-09-13T07:00:00.000Z',local:'2026-09-13T10:00:00',zone:'Asia/Jerusalem',offset:'+03:00'};
  const payload=(value:string,currency='ILS')=>({state:'received_declared',money:amount(value,currency),methodId:'manual',effective:date,evidence:{kind:'operator_declaration',attachmentState:'none_declared',note:'Fixture local',reference:''},links:[] as import('../src/lib/reg/types.js').Link[],description:'Declarado',raw:''});
  const get=<T>(kind:string,id:string)=>db.collection('reg_'+kind).doc(physicalId(ctx,id)).get().then(s=>s.data() as T);
  async function make(type:Command['type'],operationId:string|null,p:Record<string,unknown>):Promise<Command>{
    const expectedRevisions:Record<string,number>={};
    for(const kind of ['operations','agreements','allocations','methods','grants','evidence_links']){
      const rows=await db.collection('reg_'+kind).where('clientId','==',ctx.clientId).get();
      for(const row of rows.docs)expectedRevisions[kind+':'+row.data().id]=row.data().revision;
    }
    if(operationId&&!Object.hasOwn(expectedRevisions,'operations:'+operationId))expectedRevisions['operations:'+operationId]=0;
    if(p.aggregateId){const kind=type==='method.put'?'methods':type==='agreement.put'?'agreements':type==='allocation.put'?'allocations':'evidence_links';expectedRevisions[kind+':'+p.aggregateId]??=0;}
    for(const v of (p.allocations??[]) as {aggregateId:string}[])expectedRevisions['allocations:'+v.aggregateId]??=0;
    return{schemaVersion:1,epoch:1,commandId:'domain-'+(++sequence),operationId,type,expectedRevisions,payload:p};
  }
  const send=async(type:Command['type'],id:string|null,p:Record<string,unknown>)=>executeCommand(ctx,actor,await make(type,id,p));
  const reject=async(cmd:Command,code?:string)=>{
    const before=await get<Control>('control','control');
    const prior=await commandStatus(ctx,actor,cmd.commandId);
    await assert.rejects(()=>executeCommand(ctx,actor,cmd),(e:Error)=>code===undefined||e.message===code);
    assert.equal((await get<Control>('control','control')).dataRevision,before.dataRevision);
    assert.deepEqual(await commandStatus(ctx,actor,cmd.commandId),prior);
  };
  const pass=(id:string,detail:unknown)=>console.log(JSON.stringify({result:'PASS',id,detail}));
  const method={aggregateId:'manual',label:'Efectivo declarado',translations:{he:'מזומן',en:'Cash',ar:'نقد',ru:'Наличные'},currencies:['ILS','USD','JPY','KWD'],state:'enabled',provider:''};
  await send('method.put',null,method);
  await send('receipt.create','r-main',payload('100000'));
  await send('method.put',null,{...method,label:'Renombrado',state:'suspended'});
  assert.equal((await get<Operation>('operations','r-main')).method?.label,'Efectivo declarado');
  await reject(await make('receipt.create','suspended',payload('10')),'reg.method_suspended');
  await send('method.put',null,{...method,label:'Renombrado'});
  pass('R03',{historicalLabel:'Efectivo declarado',suspendedNew:'rejected'});
  await send('receipt.create','raw',{...payload('1'),state:'pending_normalization',money:null,methodId:null,effective:null,raw:'Importe y moneda no identificados'});
  await send('receipt.create','pending',{...payload('9999'),state:'pending'});
  assert.equal((await projectReg(ctx,actor)).groups[0].netMinor,'100000');
  assert.equal((await projectReg(ctx,actor)).unknown,1);
  pass('R05',{unknown:1,pendingExcluded:true});
  const agreement=(aggregateId:string,value:string|null,currency='ILS')=>({aggregateId,money:value===null?null:amount(value,currency),currency,scale:control.currencies[currency],description:'Acuerdo',links:[] as import('../src/lib/reg/types.js').Link[]});
  await send('agreement.put',null,agreement('a-main','100000'));
  await send('agreement.put',null,agreement('a-unknown',null));
  const alloc=async(aggregateId:string,receiptId:string,agreementId:string,value:string,state='active')=>({aggregateId,receiptId,agreementId,agreementRevision:(await get<Agreement>('agreements',agreementId)).revision,money:amount(value),state});
  await send('allocation.put',null,await alloc('alloc-main','r-main','a-main','100000'));
  assert.deepEqual(agreementBalance(await get('agreements','a-main')),{pendingMinor:'0',creditMinor:'0'});
  assert.deepEqual(agreementBalance(await get('agreements','a-unknown')),{pendingMinor:null,creditMinor:null});
  await send('receipt.create','usd',payload('500','USD'));
  await reject(await make('allocation.put',null,{...await alloc('wrong-unit','usd','a-unknown','100'),money:amount('100','USD')}),'reg.unit_mismatch');
  pass('R08',{unknownBalance:null,currencyRetained:'ILS',allocationNoIncome:true});
  const distribution={unallocatedMinor:'0',allocations:[{allocationId:'alloc-main',amountMinor:'10000'}]};
  const refund={...payload('10000'),state:'refund_declared',parentReceiptId:'r-main',distribution};
  await reject(await make('refund.create','refund-missing-release',refund),'reg.distribution_release_required');
  await send('refund.create','refund-main',{...refund,allocations:[await alloc('alloc-main','r-main','a-main','90000')]});
  assert.deepEqual(agreementBalance(await get('agreements','a-main')),{pendingMinor:'10000',creditMinor:'0'});
  await send('agreement.put',null,{...agreement('a-main','90000'),reason:'Rectificación explícita'});
  assert.deepEqual(agreementBalance(await get('agreements','a-main')),{pendingMinor:'0',creditMinor:'0'});
  pass('R09',{pendingBefore:'10000',pendingAfterExplicitCorrection:'0'});
  await send('receipt.create','r-race',payload('10000'));
  const competitors=await Promise.all(['c1','c2'].map(async id=>make('allocation.put',null,await alloc(id,'r-race','a-unknown','7000'))));
  const race=await Promise.allSettled(competitors.map(c=>executeCommand(ctx,actor,c)));
  assert.equal(race.filter(x=>x.status==='fulfilled').length,1);
  assert.equal((await get<Operation>('operations','r-race')).allocatedMinor,'7000');
  await send('receipt.create','r-refund-race',payload('10000'));
  const pendingRefund={...payload('7000'),state:'refund_pending',parentReceiptId:'r-refund-race',distribution:{unallocatedMinor:'7000',allocations:[] as {allocationId:string;amountMinor:string}[]}};
  const refunds=await Promise.all(['f1','f2'].map(id=>make('refund.create',id,pendingRefund)));
  const raceRefund=await Promise.allSettled(refunds.map(c=>executeCommand(ctx,actor,c)));
  assert.equal(raceRefund.filter(x=>x.status==='fulfilled').length,1);
  assert.equal((await get<Operation>('operations','r-refund-race')).reservedMinor,'7000');
  await reject(await make('allocation.put',null,await alloc('reserved-consume','r-refund-race','a-unknown','4000')),'reg.insufficient_amount');
  const winner=raceRefund.findIndex(x=>x.status==='fulfilled');
  await send('refund.correct',refunds[winner].operationId,{...pendingRefund,state:'rejected',reason:'No realizada'});
  assert.equal((await get<Operation>('operations','r-refund-race')).reservedMinor,'0');
  pass('R10',{allocationWinners:1,reservationWinners:1,releasedReservation:'0'});
  await send('receipt.create','r-net',payload('12800'));
  const netRefund={...payload('2800'),state:'refund_declared',parentReceiptId:'r-net',distribution:{unallocatedMinor:'2800',allocations:[] as {allocationId:string;amountMinor:string}[]}};
  const saved=await make('refund.create','f-net',netRefund);await executeCommand(ctx,actor,saved);
  assert.equal((await get<Operation>('operations','r-net')).refundedMinor,'2800');
  assert.deepEqual(await executeCommand(ctx,actor,saved),await commandStatus(ctx,actor,saved.commandId));
  await reject({...saved,payload:{...netRefund,money:amount('2900')}} ,'reg.command_conflict');
  await send('refund.create','f-rest',{...netRefund,money:amount('10000'),distribution:{unallocatedMinor:'10000',allocations:[] as {allocationId:string;amountMinor:string}[]}});
  assert.equal((await get<Operation>('operations','r-net')).refundedMinor,'12800');
  pass('R11/R12',{partialNet:'10000',fullNet:'0',uncertainRetry:'same receipt'});
  await send('receipt.create','r-correct',payload('12537'));
  const cut=(await get<Control>('control','control')).dataRevision;
  await send('receipt.correct','r-correct',{...payload('12000'),reason:'Cantidad mal transcrita'});
  assert.equal((await projectReg(ctx,actor,{cutRevision:cut})).operations.find(x=>x.id==='r-correct')?.money?.amountMinor,'12537');
  assert.equal((await get<Operation>('operations','r-correct')).money?.amountMinor,'12000');
  await reject(await make('receipt.correct','r-main',{...payload('80000'),reason:'Incompatible con lo asignado'}),'reg.insufficient_amount');
  await reject(await make('receipt.correct','r-main',{...payload('100000','USD'),reason:'Cambio de unidad con dependientes'}),'reg.refund_invariant');
  const history=await readEvents(ctx,actor);assert.equal(history.events.filter(e=>e.aggregateId==='r-correct').length,2);
  pass('R13/R14',{originalAtCut:'12537',effective:'12000',history:2,invalidDependencies:'no commit'});
  const correctedDate={instant:'2026-09-12T07:00:00.000Z',local:'2026-09-12T10:00:00',zone:'Asia/Jerusalem',offset:'+03:00'};
  await send('receipt.correct','r-correct',{...payload('12000'),effective:correctedDate,reason:'Fecha efectiva rectificada'});
  assert.equal((await projectReg(ctx,actor,{from:'2026-09-12',to:'2026-09-12'})).groups[0].netMinor,'12000');
  const dateEvents=(await readEvents(ctx,actor)).events.filter(e=>e.aggregateId==='r-correct');assert.ok(dateEvents.every(e=>e.recordedAt===now&&e.actor.uid===actor.uid));
  pass('R07/R16',{effective:'2026-09-12',recordedAt:now,actor:actor.uid});
  await send('receipt.create','detail-a',payload('6000'));
  await send('receipt.create','detail-b',payload('4000'));
  await send('receipt.create','aggregate',payload('10000'));
  const identity={clientId:ctx.clientId,purpose:'merchant_customer_money',environment:ctx.environment,provider:'declarado',account:'cuenta-fixture',externalId:'close-1',type:'cierre'};
  const before=(await projectReg(ctx,actor)).groups.find(g=>g.currency==='ILS')!.netMinor;
  await send('evidence.put',null,{aggregateId:'coverage',receiptId:'aggregate',identity,description:'Cierre agregado del detalle',sourceCut:'declarado:2026-09-13',state:'declared',relatedIds:[],aggregate:true});
  const after=(await projectReg(ctx,actor)).groups.find(g=>g.currency==='ILS')!.netMinor;assert.equal(BigInt(before)-BigInt(after),10000n);
  assert.equal((await projectReg(ctx,actor)).coverage,'partial');
  await send('evidence.put',null,{aggregateId:'coverage',receiptId:'aggregate',identity,description:'Detalle parcial 6000 de 10000',sourceCut:'declarado:2026-09-13',state:'declared',relatedIds:['detail-a'],aggregate:true,reason:'Correspondencia parcial'});
  const partial=await projectReg(ctx,actor);assert.equal(partial.coverage,'partial');assert.deepEqual(partial.reconciliation.unresolved,['coverage']);assert.equal(partial.groups.find(g=>g.currency==='ILS')!.netMinor,after);
  await send('evidence.put',null,{aggregateId:'coverage',receiptId:'aggregate',identity,description:'Detalle completo 6000+4000',sourceCut:'declarado:2026-09-13',state:'declared',relatedIds:['detail-a','detail-b'],aggregate:true,reason:'Completar correspondencia declarada'});
  const full=await projectReg(ctx,actor);assert.equal(full.coverage,'complete');assert.equal(full.groups.find(g=>g.currency==='ILS')!.netMinor,after);assert.ok(!full.reconciliation.excluded.includes('detail-a'));assert.ok(!full.reconciliation.excluded.includes('detail-b'));
  await reject(await make('evidence.put',null,{aggregateId:'duplicate-evidence',receiptId:'aggregate',identity,description:'Duplicado',sourceCut:'same',state:'declared',relatedIds:[],aggregate:true}),'reg.evidence_duplicate');
  await reject(await make('evidence.put',null,{aggregateId:'wrong-tenant',receiptId:'aggregate',identity:{...identity,clientId:'other'},description:'No',sourceCut:'same',state:'declared',relatedIds:[],aggregate:true}),'reg.evidence_identity');
  await send('receipt.create','candidate',payload('6000'));
  await send('evidence.put',null,{aggregateId:'review',receiptId:'detail-a',identity:{...identity,externalId:'candidate'},description:'Correspondencia por revisar',sourceCut:'fixture',state:'review',relatedIds:['candidate'],aggregate:false});
  assert.equal((await projectReg(ctx,actor)).groups.find(g=>g.currency==='ILS')!.netMinor,after);
  pass('R17/R18',{aggregateExcluded:'10000',candidateExcluded:'6000',identityConflict:'rejected'});
  // Dos declaraciones circulares no aportan detalle terminal al cierre consolidado.
  // El caso válido anterior tiene detalle incluido; aquí ambos extremos quedan excluidos.
  await send('receipt.create','cycle-a',payload('6000'));
  await send('receipt.create','cycle-b',payload('6000'));
  await send('evidence.put',null,{aggregateId:'cycle-a-evidence',receiptId:'cycle-a',identity:{...identity,externalId:'cycle-a'},description:'A declara cobertura en B',sourceCut:'fixture-circular',state:'declared',relatedIds:['cycle-b'],aggregate:true});
  const oneDirection=await projectReg(ctx,actor);
  assert.equal(oneDirection.coverage,'partial'); // La candidata review anterior sigue pendiente; no se silencia por el control circular.
  assert.deepEqual(oneDirection.reconciliation.unresolved,['review']);
  assert.deepEqual(oneDirection.reconciliation.support?.find(row=>row.operationId==='cycle-a'),{operationId:'cycle-a',terminalIds:['cycle-b'],valid:true});
  assert.ok(!oneDirection.reconciliation.excluded.includes('cycle-b'));
  await reject(await make('evidence.put',null,{aggregateId:'cycle-b-evidence',receiptId:'cycle-b',identity:{...identity,externalId:'cycle-b'},description:'B declara cobertura en A',sourceCut:'fixture-circular',state:'declared',relatedIds:['cycle-a'],aggregate:true}),'reg.evidence_cycle');
  assert.deepEqual(await projectReg(ctx,actor),oneDirection);
  pass('R18-new-cycle',{newCycle:'rejected without effects',historicalCycle:'separate reg-reconciliation-native fixture; original RED preserved in g4-05'});
  // Paquete congruente: valores nuevos explícitos en otra moneda, sin conversión implícita.
  await send('receipt.create','package-receipt',payload('10000'));
  for(const [id,currency]of [['package-ils','ILS'],['package-usd','USD']])await send('agreement.put',null,{aggregateId:id,money:amount('30000',currency),currency,scale:2,description:id,links:[]});
  const ils=await get<Agreement>('agreements','package-ils'),usd=await get<Agreement>('agreements','package-usd');
  await send('allocation.put',null,{aggregateId:'package-allocation',receiptId:'package-receipt',agreementId:ils.id,agreementRevision:ils.revision,money:amount('5000'),state:'active'});
  await send('refund.create','package-refund',{...payload('1000'),state:'refund_pending',parentReceiptId:'package-receipt',distribution:{unallocatedMinor:'1000',allocations:[]}});
  const packageBefore=(await projectReg(ctx,actor)).cutRevision;
  await reject(await make('receipt.correct','package-receipt',{...payload('20000','USD'),reason:'Incongruent unit'}),'reg.refund_invariant');
  const packageCommand=await make('receipt.correct','package-receipt',{...payload('20000','USD'),reason:'Valores nuevos declarados, no conversion',corrections:[{...payload('5000','USD'),operationId:'package-refund',reason:'Reserva expresamente corregida',state:'refund_pending',parentReceiptId:'package-receipt',distribution:{unallocatedMinor:'5000',allocations:[]}}],allocations:[{aggregateId:'package-allocation',receiptId:'package-receipt',agreementId:usd.id,agreementRevision:usd.revision,money:amount('7000','USD'),state:'active'}]});
  const packageReceipt=await executeCommand(ctx,actor,packageCommand);assert.equal(packageReceipt.eventIds.length,5);
  const corrected=await get<Operation>('operations','package-receipt');assert.deepEqual([corrected.money?.currency,corrected.money?.amountMinor,corrected.allocatedMinor,corrected.reservedMinor],['USD','20000','7000','5000']);assert.equal((await get<Agreement>('agreements',ils.id)).allocatedMinor,'0');assert.equal((await get<Agreement>('agreements',usd.id)).allocatedMinor,'7000');
  assert.equal((await projectReg(ctx,actor,{cutRevision:packageBefore})).operations.find(op=>op.id==='package-receipt')?.money?.currency,'ILS');
  await send('refund.correct','package-refund',{...payload('5000','USD'),reason:'Declarar devolucion recibida',state:'refund_declared',parentReceiptId:'package-receipt',distribution:{unallocatedMinor:'5000',allocations:[]}});
  await send('refund.correct','package-refund',{...payload('3000','USD'),reason:'Correccion explicita de devolucion',state:'refund_declared',parentReceiptId:'package-receipt',distribution:{unallocatedMinor:'3000',allocations:[]}});
  assert.equal((await get<Operation>('operations','package-receipt')).refundedMinor,'3000');
  const currentAllocation=await get<Allocation>('allocations','package-allocation'),currentAgreement=await get<Agreement>('agreements',usd.id);
  await send('receipt.correct','package-receipt',{...payload('20000','USD'),reason:'Anular declaraciones erroneas con dependientes',state:'void',corrections:[{...payload('3000','USD'),operationId:'package-refund',reason:'Anular declaracion hija',state:'void',parentReceiptId:'package-receipt',distribution:{unallocatedMinor:'3000',allocations:[]}}],allocations:[{...currentAllocation,aggregateId:currentAllocation.id,state:'released',agreementRevision:currentAgreement.revision}]});
  const voided=await get<Operation>('operations','package-receipt');assert.deepEqual([voided.state,voided.allocatedMinor,voided.refundedMinor,voided.reservedMinor],['void','0','0','0']);assert.equal((await get<Operation>('operations','package-refund')).state,'void');
  pass('R14-package',{incongruent:'rejected without writes',congruentEvents:5,newUnit:'USD explicit values',receipt:'20000',allocation:'7000',pendingRefund:'5000',refundCorrection:'3000',void:'parent/refund void, allocation released, history preserved'});
  await send('receipt.create','limit-receipt',payload('50000'));await send('agreement.put',null,{aggregateId:'limit-agreement',money:amount('50000'),currency:'ILS',scale:2,description:'Limite positivo',links:[]});
  const fifty=Array.from({length:50},(_,i)=>({aggregateId:'limit-allocation-'+i,receiptId:'limit-receipt',agreementId:'limit-agreement',agreementRevision:1,money:amount('1000'),state:'active'}));
  const limitReceipt=await send('receipt.correct','limit-receipt',{...payload('50000'),reason:'Cincuenta asignaciones explicitas',allocations:fifty});
  assert.equal(limitReceipt.eventIds.length,52);assert.equal((await get<Operation>('operations','limit-receipt')).allocatedMinor,'50000');assert.equal((await get<Agreement>('agreements','limit-agreement')).allocatedMinor,'50000');
  const actualFifty=(await db.collection('reg_allocations').where('clientId','==',ctx.clientId).get()).docs.map(doc=>doc.data()).filter(row=>row.receiptId==='limit-receipt');assert.equal(actualFifty.length,50);assert.equal(actualFifty.reduce((sum,row)=>sum+BigInt(row.money.amountMinor),0n),50000n);
  pass('R27-positive50',{allocations:50,events:52,totalMinor:'50000',nativeTransaction:'accepted'});
  const over=await make('receipt.correct','r-correct',{...payload('12000'),reason:'Fuera de límite',allocations:Array.from({length:51},()=>({}))});
  await reject(over,'reg.dependents_limit');
  await reject(await make('receipt.correct','r-correct',{...payload('12000'),reason:'x'.repeat(128*1024)}),'reg.payload_limit');
  pass('R27-subset',{dependents51:'rejected',payloadOversize:'rejected',remaining:'positive50 and role matrix'});
  const final=await projectReg(ctx,actor),ids=final.operations.map(x=>x.id);
  await send('control.mode',null,{mode:'read_only',reason:'Reversa conserva dinero'});
  assert.deepEqual((await projectReg(ctx,actor)).operations.map(x=>x.id),ids);
  assert.deepEqual(await executeCommand(ctx,actor,saved),await commandStatus(ctx,actor,saved.commandId));
  await reject(await make('receipt.create','after-reverse',payload('10')),'reg.read_only');
  pass('R28-subset',{readOnlyPreservesIds:ids.length,retryAcceptedStillRecoverable:true,remaining:'legacy fence and physical restore'});
}
