import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import type { Firestore } from 'firebase-admin/firestore';
import { executeCommand, readEvents } from '../src/lib/reg/store.js';
import { projectReg } from '../src/lib/reg/projection.js';
import { regCsv } from '../src/lib/reg/view.js';
import { membershipVersion, physicalId, principalId, type RegContext } from '../src/lib/reg/authority.js';
import { CAPABILITIES, type Actor, type Command, type Control, type Grant } from '../src/lib/reg/types.js';
import { historicalCircular } from './reg-historical-native.js';
import type { reconcileEvidence } from '../src/lib/reg/reconciliation.js';

/** Contraejemplos de la revisión: valores literales, persistencia nativa y corte por tenant propio. */
export async function runReconciliationNative(db:Firestore,base:RegContext,output:string):Promise<void>{
  const ctx={...base,clientId:'tenant-reconciliation'},actor:Actor={issuer:ctx.issuer,uid:'reconciliation-owner',email:'reconciliation@example.invalid'},now=ctx.now!();
  const member={clientId:ctx.clientId,role:'owner',status:'active',invitedAt:now};
  const control:Control={clientId:ctx.clientId,environment:ctx.environment,authorityId:ctx.authorityId,schemaVersion:1,epoch:1,dataRevision:0,mode:'ready',minClientVersion:1,currencies:{ILS:2}};
  const grant:Grant={purpose:'merchant_customer_money',id:principalId(actor),clientId:ctx.clientId,environment:ctx.environment,schemaVersion:1,revision:1,authoredBy:actor,recordedAt:now,...actor,role:'owner',state:'active',scope:'all',capabilities:[...CAPABILITIES],membershipVersion:membershipVersion(member),epoch:1};
  await db.collection('admin_users').doc(actor.email).set(member);
  await db.collection('reg_legacy_fence').doc(ctx.clientId).set({authorityId:ctx.authorityId,environment:ctx.environment,epoch:1,manualMoney:'blocked'});
  await db.collection('reg_control').doc(physicalId(ctx,'control')).set(control);
  await db.collection('reg_grants').doc(physicalId(ctx,grant.id)).set(grant);
  let sequence=0;
  async function command(type:Command['type'],operationId:string|null,payload:Record<string,unknown>):Promise<Command>{
    const kind=type==='receipt.create'?'operations':type==='method.put'?'methods':'evidence_links',id=operationId??String(payload.aggregateId);
    const previous=(await db.collection('reg_'+kind).doc(physicalId(ctx,id)).get()).data();
    return{schemaVersion:1,epoch:1,commandId:'reconciliation-'+(++sequence),operationId,type,expectedRevisions:{[kind+':'+id]:previous?.revision??0},payload};
  }
  const send=async(type:Command['type'],id:string|null,payload:Record<string,unknown>)=>executeCommand(ctx,actor,await command(type,id,payload));
  await send('method.put',null,{aggregateId:'cash',label:'Declarado',translations:{},state:'enabled',currencies:['ILS'],provider:''});
  const receipt=async(id:string,amountMinor:string)=>send('receipt.create',id,{state:'received_declared',money:{amountMinor,currency:'ILS',scale:2},methodId:'cash',effective:{instant:'2026-09-13T07:00:00.000Z',local:'2026-09-13T10:00:00',zone:'Asia/Jerusalem',offset:'+03:00'},evidence:{kind:'operator_declaration',attachmentState:'none_declared',reference:'',note:''},description:id,links:[] as unknown[],raw:''});
  const evidence=(aggregateId:string,receiptId:string,relatedIds:string[],aggregate=true,state='declared')=>({aggregateId,receiptId,relatedIds,aggregate,state,identity:{clientId:ctx.clientId,purpose:'merchant_customer_money',environment:ctx.environment,provider:'manual',account:'fixture',externalId:aggregateId,type:'declaration'},description:aggregateId,sourceCut:'fixture-2026-09-13',reason:'Correspondencia explícita'});
  await receipt('chain-top','10000');await receipt('chain-middle','10000');await receipt('chain-a','6000');await receipt('chain-b','4000');
  await send('evidence.put',null,evidence('chain-lower','chain-middle',['chain-a','chain-b']));
  await send('evidence.put',null,evidence('chain-upper','chain-top',['chain-middle']));
  const chain=await projectReg(ctx,actor);assert.equal(chain.groups[0].netMinor,'10000');assert.equal(chain.coverage,'complete');
  console.log(JSON.stringify({result:'PASS',id:'SP01-chain',cut:chain.cutRevision,includedMinor:'10000',excluded:chain.reconciliation.excluded}));
  await receipt('diamond-top','20000');await receipt('diamond-left','10000');await receipt('diamond-right','10000');await receipt('diamond-leaf','10000');
  await send('evidence.put',null,evidence('diamond-l','diamond-left',['diamond-leaf']));
  await send('evidence.put',null,evidence('diamond-r','diamond-right',['diamond-leaf']));
  const beforeTop=(await projectReg(ctx,actor)).cutRevision;
  await send('evidence.put',null,evidence('diamond-t','diamond-top',['diamond-left','diamond-right']));
  const diamond=await projectReg(ctx,actor),raw=await readEvents(ctx,actor);
  console.log(JSON.stringify({result:'OBSERVATION',id:'SP01-shared-terminal',expectedCoverage:'partial',actualCoverage:diamond.coverage,netMinor:diamond.groups[0].netMinor,unresolved:diamond.reconciliation.unresolved,cut:diamond.cutRevision,events:raw.events.filter(e=>e.aggregateId.startsWith('diamond'))}));
  assert.equal(diamond.groups[0].netMinor,'20000'); // Cadena10000 + terminal10000; jamás20000 de respaldo para el diamante.
  assert.equal(diamond.coverage,'partial','SP01: dos ramas no pueden reutilizar el mismo terminal como respaldo de200');
  assert.ok(diamond.reconciliation.unresolved?.includes('diamond-t'));
  const disarmed=createRequire(output+'/runner.cjs')(output+'/mutant-reconciliation.cjs') as {reconcileEvidence:typeof reconcileEvidence};
  const defective=disarmed.reconcileEvidence(diamond.operations,diamond.evidence);assert.ok(!defective.unresolved.includes('diamond-t'));assert.equal(defective.support.find(row=>row.operationId==='diamond-top')?.valid,true);
  assert.equal(disarmed.reconcileEvidence(chain.operations,chain.evidence).unresolved.length,0);
  console.log(JSON.stringify({result:'PASS',id:'SP01-mutant-support',positiveChain:'valid',diamond:'production rejects support, disarmed validation falsely admits it',terminalCount:diamond.reconciliation.support?.find(row=>row.operationId==='diamond-top')?.terminalIds.length}));
  const historical=await projectReg(ctx,actor,{cutRevision:beforeTop});assert.equal(historical.coverage,'complete');assert.equal(historical.groups[0].netMinor,'40000');
  await receipt('cycle-a','6000');await receipt('cycle-b','6000');
  await send('evidence.put',null,evidence('cycle-first','cycle-a',['cycle-b']));
  const cycleCommand=await command('evidence.put',null,evidence('cycle-second','cycle-b',['cycle-a']));
  const beforeCycle=(await readEvents(ctx,actor)).events;
  await assert.rejects(()=>executeCommand(ctx,actor,cycleCommand),(e:Error)=>e.message==='reg.evidence_cycle');
  assert.deepEqual((await readEvents(ctx,actor)).events,beforeCycle);
  assert.equal((await db.collection('reg_commands').doc(physicalId(ctx,cycleCommand.commandId)).get()).exists,false);
  console.log(JSON.stringify({result:'PASS',id:'SP01-cycle-write',rejectedWithoutWrites:true}));
  const mutant=createRequire(output+'/runner.cjs')(output+'/mutant-store.cjs') as {executeCommand:typeof executeCommand};
  await mutant.executeCommand(ctx,actor,cycleCommand);
  assert.equal((await db.collection('reg_commands').doc(physicalId(ctx,cycleCommand.commandId)).get()).exists,true);
  const historicalCycle=await projectReg(ctx,actor);
  assert.ok(historicalCycle.reconciliation.unresolved?.includes('cycle-first'));
  assert.ok(historicalCycle.reconciliation.unresolved?.includes('cycle-second'));
  assert.equal(historicalCycle.coverage,'partial');
  assert.equal(historicalCycle.operations.filter(op=>op.id.startsWith('cycle-')).length,2);
  console.log(JSON.stringify({result:'PASS',id:'SP01-mutant-and-historical-read',mutantAcceptedForbiddenCycle:true,historicalCoverage:'partial',unresolved:historicalCycle.reconciliation.unresolved,originals:2}));
  await receipt('excluded-top','10000');await receipt('excluded-detail','10000');await receipt('representative','10000');
  await send('evidence.put',null,evidence('excluded-parent','excluded-top',['excluded-detail']));
  await send('evidence.put',null,evidence('duplicate-resolution','representative',['excluded-detail'],false,'review'));
  const pending=await projectReg(ctx,actor);
  assert.ok(pending.reconciliation.unresolved?.includes('excluded-parent'));
  assert.ok(pending.reconciliation.unresolved?.includes('duplicate-resolution'));
  const pendingCut=pending.cutRevision;
  await send('evidence.put',null,evidence('duplicate-resolution','representative',['excluded-detail'],false,'declared'));
  const declared=await projectReg(ctx,actor);
  assert.ok(!declared.reconciliation.unresolved?.includes('excluded-parent'));
  assert.ok(!declared.reconciliation.unresolved?.includes('duplicate-resolution'));
  assert.deepEqual(declared.reconciliation.support?.find(row=>row.operationId==='excluded-top'),{operationId:'excluded-top',terminalIds:['representative'],valid:true});
  assert.ok((await projectReg(ctx,actor,{cutRevision:pendingCut})).reconciliation.unresolved?.includes('excluded-parent'));
  const beforeIndependent=BigInt(declared.groups[0].netMinor);
  await receipt('same-amount-independent','10000');
  assert.equal(BigInt((await projectReg(ctx,actor)).groups[0].netMinor)-beforeIndependent,10000n);
  console.log(JSON.stringify({result:'PASS',id:'SP01-duplicate-review-history',pendingInvalidatesParent:true,declaredTerminal:'representative',historicalPendingPreserved:true,equalAmountNotDeduplicated:true}));
  const beforeReadonly=await readEvents(ctx,actor);
  await executeCommand(ctx,actor,{schemaVersion:1,epoch:1,commandId:'read-only-export',operationId:null,type:'control.mode',expectedRevisions:{},payload:{mode:'read_only',reason:'Salida con cobertura parcial'}});
  const partial=await projectReg(ctx,actor,{cap:'export'}),history=await readEvents(ctx,actor,{cutRevision:partial.cutRevision,cap:'export'});
  const csv=regCsv(partial,history.events,event=>physicalId(ctx,event.id));
  assert.ok(csv.includes('"partial"'));assert.ok(csv.includes('"cycle-a"'));assert.ok(csv.includes('"cycle-b"'));
  assert.ok(csv.includes('"excludedFromTotal"'));assert.ok(csv.includes('no complete balance'));
  assert.equal(csv.split('\r\n').filter(line=>line.startsWith('"receipt"')).length,partial.operations.length);
  assert.equal(history.events.length,beforeReadonly.events.length+1);
  await assert.rejects(()=>receipt('after-read-only','100'),(e:Error)=>e.message==='reg.read_only');
  await db.collection('reg_grants').doc(physicalId(ctx,grant.id)).update({capabilities:CAPABILITIES.filter(cap=>cap!=='export'),revision:2});
  await assert.rejects(()=>projectReg(ctx,actor,{cap:'export'}),(e:Error)=>e.message==='reg.forbidden');
  await assert.rejects(()=>projectReg({...ctx,loadDb:async()=>{throw new Error('fixture-source-down');}},actor));
  console.log(JSON.stringify({result:'PASS',id:'SP04-partial-export-readonly',operations:partial.operations.length,events:history.events.length,coverage:'partial',unauthorizedExport:'rejected',newMoney:'rejected',sourceFailure:'error not empty'}));
  await historicalCircular(db,base);
}
