/**
 * Demo data for CRM tabs when TOUR_CONFIG.isDemoMode is true.
 * Gives prospects a realistic preview of how the system looks with real data.
 */
import type { Appointment, Customer, ContactInboxItem } from "../types";
import { format, subDays, subHours, addDays } from "date-fns";
import { siteConfig } from "./site";
import type { Task } from "../lib/tasks";

const now = new Date();
const today = format(now, "yyyy-MM-dd");
const yesterday = format(subDays(now, 1), "yyyy-MM-dd");
const twoDaysAgo = format(subDays(now, 2), "yyyy-MM-dd");
const threeDaysAgo = format(subDays(now, 3), "yyyy-MM-dd");
const fiveDaysAgo = format(subDays(now, 5), "yyyy-MM-dd");

const staffId = siteConfig.staff[0]?.id ?? "staff-1";
const clientId = "demo";

export const DEMO_APPOINTMENTS: Appointment[] = [
  {
    id: "demo-apt-1",
    clientId,
    customerName: "David Cohen",
    customerEmail: "david.c@gmail.com",
    customerPhone: "054-555-1234",
    serviceId: siteConfig.services[0]?.id ?? "haircut",
    staffId,
    date: today,
    time: "10:00",
    duration: siteConfig.services[0]?.duration ?? 30,
    status: "confirmed",
    type: "appointment",
    amountPaidCents: (siteConfig.services[0]?.price ?? 30) * 100,
    paymentStatus: "paid",
    createdAt: subDays(now, 1),
  },
  {
    id: "demo-apt-2",
    clientId,
    customerName: "Yossi Levi",
    customerEmail: "yossi.l@gmail.com",
    customerPhone: "052-555-5678",
    serviceId: siteConfig.services[4]?.id ?? siteConfig.services[1]?.id ?? "beard-sculpt",
    staffId: siteConfig.staff[1]?.id ?? staffId,
    date: today,
    time: "11:30",
    duration: siteConfig.services[4]?.duration ?? siteConfig.services[1]?.duration ?? 75,
    status: "pending",
    type: "appointment",
    createdAt: subHours(now, 3),
  },
  {
    id: "demo-apt-3",
    clientId,
    customerName: "Amit Shapira",
    customerEmail: "amit.s@gmail.com",
    customerPhone: "050-555-9012",
    serviceId: siteConfig.services[2]?.id ?? "straight-shave",
    staffId,
    date: today,
    time: "14:00",
    duration: siteConfig.services[2]?.duration ?? 35,
    status: "confirmed",
    type: "consultation",
    createdAt: subDays(now, 2),
  },
  {
    id: "demo-apt-4",
    clientId,
    customerName: "Michael Ben-Ari",
    customerEmail: "michael.b@gmail.com",
    customerPhone: "053-555-3456",
    serviceId: siteConfig.services[1]?.id ?? "beard-sculpt",
    staffId: siteConfig.staff[2]?.id ?? staffId,
    date: yesterday,
    time: "16:00",
    duration: siteConfig.services[1]?.duration ?? 25,
    status: "completed",
    type: "appointment",
    amountPaidCents: (siteConfig.services[1]?.price ?? 25) * 100,
    paymentStatus: "paid",
    createdAt: subDays(now, 3),
  },
  {
    id: "demo-apt-5",
    clientId,
    customerName: "Noam Katz",
    customerEmail: "noam.k@gmail.com",
    customerPhone: "058-555-7890",
    serviceId: siteConfig.services[0]?.id ?? "haircut",
    staffId,
    date: twoDaysAgo,
    time: "09:30",
    duration: siteConfig.services[0]?.duration ?? 30,
    status: "completed",
    type: "appointment",
    amountPaidCents: (siteConfig.services[0]?.price ?? 30) * 100,
    paymentStatus: "paid",
    createdAt: subDays(now, 4),
  },
  {
    id: "demo-apt-6",
    clientId,
    customerName: "Sara Mizrahi",
    customerEmail: "sara.m@gmail.com",
    customerPhone: "054-555-2222",
    serviceId: siteConfig.services[0]?.id ?? "haircut",
    staffId,
    date: yesterday,
    time: "12:00",
    duration: 30,
    status: "completed",
    type: "meeting",
    createdAt: subDays(now, 3),
  },
  {
    id: "demo-apt-7",
    clientId,
    customerName: "Tali Berman",
    customerEmail: "tali.b@gmail.com",
    customerPhone: "050-555-3333",
    serviceId: siteConfig.services[3]?.id ?? siteConfig.services[0]?.id ?? "haircut",
    staffId: siteConfig.staff[1]?.id ?? staffId,
    date: threeDaysAgo,
    time: "15:00",
    duration: siteConfig.services[3]?.duration ?? 45,
    status: "completed",
    type: "appointment",
    amountPaidCents: (siteConfig.services[3]?.price ?? 45) * 100,
    paymentStatus: "paid",
    createdAt: subDays(now, 5),
  },
  {
    id: "demo-apt-8",
    clientId,
    customerName: "Oren Avraham",
    customerEmail: "oren.a@gmail.com",
    customerPhone: "058-555-4444",
    serviceId: siteConfig.services[0]?.id ?? "haircut",
    staffId,
    date: fiveDaysAgo,
    time: "10:30",
    duration: siteConfig.services[0]?.duration ?? 30,
    status: "cancelled",
    type: "appointment",
    createdAt: subDays(now, 7),
  },
];

/**
 * 25 demo customers distributed across the 5 pipeline stages (Bloque F):
 *   • 5 leads      — recent inquiries, no contact yet
 *   • 5 contacted  — owner reached out, awaiting reply / booking
 *   • 5 scheduled  — have a future appointment in DEMO_APPOINTMENTS
 *   • 7 converted  — visitCount >= 1, real history
 *   • 3 lost       — explicitly marked
 */
export const DEMO_CUSTOMERS: Customer[] = [
  // ── Converted (existing 5 + 2 more) ────────────────────────────────────────
  {
    id: "demo-cust-1",
    clientId,
    fullName: "David Cohen",
    email: "david.c@gmail.com",
    phone: "054-555-1234",
    visitCount: 8,
    source: "booking",
    stage: "converted",
    tags: ["VIP", "regular"],
    notes: "Always books the fade. Prefers Tuesdays.",
    lastVisitAt: subDays(now, 7),
    createdAt: subDays(now, 90),
    updatedAt: subDays(now, 7),
  },
  {
    id: "demo-cust-2",
    clientId,
    fullName: "Yossi Levi",
    email: "yossi.l@gmail.com",
    phone: "052-555-5678",
    visitCount: 3,
    source: "booking",
    stage: "converted",
    tags: ["beard-care"],
    notes: "",
    lastVisitAt: subDays(now, 14),
    createdAt: subDays(now, 60),
    updatedAt: subDays(now, 14),
  },
  {
    id: "demo-cust-3",
    clientId,
    fullName: "Amit Shapira",
    email: "amit.s@gmail.com",
    phone: "050-555-9012",
    visitCount: 12,
    source: "booking",
    stage: "converted",
    tags: ["VIP", "frequent"],
    notes: "",
    lastVisitAt: subDays(now, 2),
    createdAt: subDays(now, 180),
    updatedAt: subDays(now, 2),
  },
  {
    id: "demo-cust-4",
    clientId,
    fullName: "Michael Ben-Ari",
    email: "michael.b@gmail.com",
    phone: "053-555-3456",
    visitCount: 1,
    source: "manual",
    stage: "converted",
    tags: ["first-visit"],
    notes: "Came via walk-in. Liked the cold towel finish.",
    lastVisitAt: subDays(now, 1),
    createdAt: subDays(now, 5),
    updatedAt: subDays(now, 5),
  },
  {
    id: "demo-cust-5",
    clientId,
    fullName: "Noam Katz",
    email: "noam.k@gmail.com",
    phone: "058-555-7890",
    visitCount: 5,
    source: "booking",
    stage: "converted",
    tags: ["regular"],
    notes: "",
    lastVisitAt: subDays(now, 3),
    createdAt: subDays(now, 120),
    updatedAt: subDays(now, 3),
  },
  {
    id: "demo-cust-6",
    clientId,
    fullName: "Tomer Aharon",
    email: "tomer.a@gmail.com",
    phone: "050-555-1111",
    visitCount: 2,
    source: "instagram",
    stage: "converted",
    tags: ["instagram"],
    notes: "",
    lastVisitAt: subDays(now, 21),
    createdAt: subDays(now, 45),
    updatedAt: subDays(now, 21),
  },
  {
    id: "demo-cust-7",
    clientId,
    fullName: "Roi Mizrahi",
    email: "roi.m@gmail.com",
    phone: "054-555-2222",
    visitCount: 4,
    source: "referral",
    stage: "converted",
    tags: ["referral", "high-LTV"],
    notes: "Referred by David Cohen.",
    lastVisitAt: subDays(now, 10),
    createdAt: subDays(now, 70),
    updatedAt: subDays(now, 10),
  },

  // ── Scheduled (5 — have an upcoming/pending appt) ──────────────────────────
  {
    id: "demo-cust-8",
    clientId,
    fullName: "Eli Bashan",
    email: "eli.b@gmail.com",
    phone: "058-555-3333",
    visitCount: 0,
    source: "web",
    stage: "scheduled",
    tags: ["new"],
    notes: "Booked online this week.",
    createdAt: subDays(now, 4),
    updatedAt: subDays(now, 1),
  },
  {
    id: "demo-cust-9",
    clientId,
    fullName: "Avi Shimoni",
    email: "avi.s@gmail.com",
    phone: "053-555-4444",
    visitCount: 0,
    source: "whatsapp",
    stage: "scheduled",
    tags: [],
    notes: "Coming Friday for first cut.",
    createdAt: subDays(now, 3),
    updatedAt: subDays(now, 3),
  },
  {
    id: "demo-cust-10",
    clientId,
    fullName: "Yair Sharabi",
    email: "yair.s@gmail.com",
    phone: "050-555-5555",
    visitCount: 0,
    source: "web",
    stage: "scheduled",
    tags: ["consultation"],
    notes: "",
    createdAt: subDays(now, 2),
    updatedAt: subDays(now, 2),
  },
  {
    id: "demo-cust-11",
    clientId,
    fullName: "Ben Dahan",
    email: "ben.d@gmail.com",
    phone: "054-555-6666",
    visitCount: 0,
    source: "google",
    stage: "scheduled",
    tags: [],
    notes: "Found us on Google Maps.",
    createdAt: subDays(now, 6),
    updatedAt: subDays(now, 2),
  },
  {
    id: "demo-cust-12",
    clientId,
    fullName: "Or Hadad",
    email: "or.h@gmail.com",
    phone: "052-555-7777",
    visitCount: 0,
    source: "instagram",
    stage: "scheduled",
    tags: ["instagram"],
    notes: "Sent DM after seeing portfolio.",
    createdAt: subDays(now, 5),
    updatedAt: subDays(now, 1),
  },

  // ── Contacted (5 — owner reached out, awaiting reply) ──────────────────────
  {
    id: "demo-cust-13",
    clientId,
    fullName: "Itay Levi",
    email: "itay.l@gmail.com",
    phone: "058-555-8888",
    visitCount: 0,
    source: "whatsapp",
    stage: "contacted",
    tags: [],
    notes: "Sent quote, waiting for date confirmation.",
    lastContactedAt: subDays(now, 1),
    createdAt: subDays(now, 4),
    updatedAt: subDays(now, 1),
  },
  {
    id: "demo-cust-14",
    clientId,
    fullName: "Shai Buzaglo",
    email: "shai.b@gmail.com",
    phone: "050-555-9999",
    visitCount: 0,
    source: "instagram",
    stage: "contacted",
    tags: ["instagram"],
    notes: "Replied with Friday slots.",
    lastContactedAt: subDays(now, 2),
    createdAt: subDays(now, 5),
    updatedAt: subDays(now, 2),
  },
  {
    id: "demo-cust-15",
    clientId,
    fullName: "Lior Peretz",
    email: "lior.p@gmail.com",
    phone: "054-555-1212",
    visitCount: 0,
    source: "web",
    stage: "contacted",
    tags: ["follow-up"],
    notes: "Asked about beard treatment package.",
    lastContactedAt: subDays(now, 3),
    createdAt: subDays(now, 7),
    updatedAt: subDays(now, 3),
  },
  {
    id: "demo-cust-16",
    clientId,
    fullName: "Eyal Madar",
    email: "eyal.m@gmail.com",
    phone: "058-555-1313",
    visitCount: 0,
    source: "referral",
    stage: "contacted",
    tags: ["referral"],
    notes: "Recommended by Amit. Texted intro.",
    lastContactedAt: subHours(now, 8),
    createdAt: subDays(now, 1),
    updatedAt: subHours(now, 8),
  },
  {
    id: "demo-cust-17",
    clientId,
    fullName: "Doron Yaakov",
    email: "doron.y@gmail.com",
    phone: "052-555-1414",
    visitCount: 0,
    source: "google",
    stage: "contacted",
    tags: [],
    notes: "Asked for price list yesterday.",
    lastContactedAt: subDays(now, 1),
    createdAt: subDays(now, 2),
    updatedAt: subDays(now, 1),
  },

  // ── Leads (5 — fresh, no contact yet) ──────────────────────────────────────
  {
    id: "demo-cust-18",
    clientId,
    fullName: "Niv Saban",
    email: "niv.s@gmail.com",
    phone: "054-555-1515",
    visitCount: 0,
    source: "web",
    stage: "lead",
    tags: [],
    notes: "",
    createdAt: subHours(now, 4),
    updatedAt: subHours(now, 4),
  },
  {
    id: "demo-cust-19",
    clientId,
    fullName: "Omer Bashari",
    email: "omer.b@gmail.com",
    phone: "058-555-1616",
    visitCount: 0,
    source: "whatsapp",
    stage: "lead",
    tags: ["new"],
    notes: "WhatsApp inquiry, hasn't replied to auto-message.",
    createdAt: subHours(now, 2),
    updatedAt: subHours(now, 2),
  },
  {
    id: "demo-cust-20",
    clientId,
    fullName: "Yaron Tal",
    email: "yaron.t@gmail.com",
    phone: "050-555-1717",
    visitCount: 0,
    source: "instagram",
    stage: "lead",
    tags: ["instagram"],
    notes: "",
    createdAt: subDays(now, 1),
    updatedAt: subDays(now, 1),
  },
  {
    id: "demo-cust-21",
    clientId,
    fullName: "Idan Vaknin",
    email: "idan.v@gmail.com",
    phone: "053-555-1818",
    visitCount: 0,
    source: "google",
    stage: "lead",
    tags: [],
    notes: "",
    createdAt: subHours(now, 6),
    updatedAt: subHours(now, 6),
  },
  {
    id: "demo-cust-22",
    clientId,
    fullName: "Gilad Cohen",
    email: "gilad.c@gmail.com",
    phone: "054-555-1919",
    visitCount: 0,
    source: "referral",
    stage: "lead",
    tags: ["referral"],
    notes: "Friend mentioned us — hasn't replied yet.",
    createdAt: subHours(now, 10),
    updatedAt: subHours(now, 10),
  },

  // ── Lost (3) ───────────────────────────────────────────────────────────────
  {
    id: "demo-cust-23",
    clientId,
    fullName: "Ariel Mazor",
    email: "ariel.m@gmail.com",
    phone: "058-555-2020",
    visitCount: 0,
    source: "web",
    stage: "lost",
    tags: ["no-show"],
    notes: "Booked, didn't show up. No reply since.",
    lastContactedAt: subDays(now, 14),
    createdAt: subDays(now, 30),
    updatedAt: subDays(now, 14),
  },
  {
    id: "demo-cust-24",
    clientId,
    fullName: "Hagai Solomon",
    email: "hagai.s@gmail.com",
    phone: "050-555-2121",
    visitCount: 0,
    source: "whatsapp",
    stage: "lost",
    tags: ["price-sensitive"],
    notes: "Asked for discount we couldn't match.",
    lastContactedAt: subDays(now, 20),
    createdAt: subDays(now, 25),
    updatedAt: subDays(now, 20),
  },
  {
    id: "demo-cust-25",
    clientId,
    fullName: "Sagi Levi",
    email: "sagi.l@gmail.com",
    phone: "054-555-2222",
    visitCount: 0,
    source: "instagram",
    stage: "lost",
    tags: [],
    notes: "Stopped replying after the second message.",
    lastContactedAt: subDays(now, 40),
    createdAt: subDays(now, 50),
    updatedAt: subDays(now, 40),
  },
];

export const DEMO_INBOX: ContactInboxItem[] = [
  {
    id: "demo-msg-1",
    clientId,
    name: "Eyal Mizrachi",
    email: "eyal.m@gmail.com",
    phone: "054-555-4321",
    subject: "Walk-in availability?",
    message: "Hi, do you accept walk-ins on Fridays? I'd like to come around 3pm if possible.",
    source: "web",
    status: "new",
    createdAt: subHours(now, 2),
  },
  {
    id: "demo-msg-2",
    clientId,
    name: "David Cohen",
    email: "david.c@gmail.com",
    subject: "Rescheduling",
    message: "Hey, I need to move my appointment from Thursday to Friday if there's a slot. Thanks!",
    source: "chat",
    status: "read",
    createdAt: subDays(now, 1),
  },
  {
    id: "demo-msg-3",
    clientId,
    name: "Sarah Goldstein",
    email: "sarah.g@gmail.com",
    phone: "050-555-8765",
    subject: "Gift card",
    message: "Hi! Do you sell gift cards? I want to buy one for my husband's birthday.",
    source: "web",
    status: "replied",
    repliedAt: subHours(now, 18),
    createdAt: subDays(now, 2),
  },
  {
    id: "demo-msg-wa-1",
    clientId,
    name: "Yael Avraham",
    email: "yael.a@noemail.local",
    phone: "+972541234567",
    subject: "WhatsApp inquiry",
    message: "Hi! Do you have any availability for a haircut tomorrow afternoon?",
    source: "whatsapp",
    status: "new",
    createdAt: subHours(now, 1),
  },
];

// ── Tasks (Bloque J) ──────────────────────────────────────────────────────────
// 8 tasks distributed across the 4 kanban statuses, several assignees and
// priorities, plus a couple linked to demo customers. Drives both the
// TasksTab view and the AI assistant's demo-mode tools.
const demoOwnerEmail = siteConfig.adminEmail || "owner@demo.local";
const demoManagerEmail = "manager@demo.local";
const demoStaffEmail = "staff@demo.local";

export const DEMO_TASKS: Task[] = [
  {
    id: "demo-task-1",
    clientId,
    title: "Confirm wax delivery for next week",
    description: "Supplier promised Wednesday — chase if not confirmed by Monday.",
    status: "pending",
    priority: "high",
    dueDate: addDays(now, 2).toISOString(),
    assignedTo: demoOwnerEmail,
    createdBy: demoOwnerEmail,
    createdAt: subHours(now, 6).toISOString(),
    updatedAt: subHours(now, 6).toISOString(),
    shared: true,
    tags: ["inventory", "follow-up"],
  },
  {
    id: "demo-task-2",
    clientId,
    title: "Call Ana Levi about her color preference",
    description: "She left a voicemail asking about ammonia-free options.",
    status: "pending",
    priority: "medium",
    dueDate: addDays(now, 1).toISOString(),
    assignedTo: demoStaffEmail,
    createdBy: demoOwnerEmail,
    createdAt: subDays(now, 1).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
    shared: true,
    relatedCustomerId: "demo-cust-3",
    tags: ["customer"],
  },
  {
    id: "demo-task-3",
    clientId,
    title: "Restock front display — empty shelves",
    status: "pending",
    priority: "low",
    assignedTo: demoStaffEmail,
    createdBy: demoStaffEmail,
    createdAt: subHours(now, 3).toISOString(),
    updatedAt: subHours(now, 3).toISOString(),
    shared: false,
    tags: ["inventory"],
  },
  {
    id: "demo-task-4",
    clientId,
    title: "Draft the May newsletter",
    description: "Cover the new color line + the loyalty program tweak.",
    status: "in_progress",
    priority: "medium",
    dueDate: addDays(now, 5).toISOString(),
    assignedTo: demoManagerEmail,
    createdBy: demoOwnerEmail,
    createdAt: subDays(now, 3).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
    shared: true,
    tags: ["marketing"],
  },
  {
    id: "demo-task-5",
    clientId,
    title: "Review last month's no-show list",
    description: "Flag repeat offenders for the deposit-required tag.",
    status: "in_progress",
    priority: "high",
    assignedTo: demoOwnerEmail,
    createdBy: demoOwnerEmail,
    createdAt: subDays(now, 2).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
    shared: false,
    tags: ["customer", "policy"],
  },
  {
    id: "demo-task-6",
    clientId,
    title: "Send thank-you message to Eyal Mizrachi",
    status: "done",
    priority: "low",
    assignedTo: demoStaffEmail,
    createdBy: demoStaffEmail,
    createdAt: subDays(now, 4).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
    completedAt: subDays(now, 1).toISOString(),
    shared: true,
    relatedCustomerId: "demo-cust-1",
    tags: ["customer"],
  },
  {
    id: "demo-task-7",
    clientId,
    title: "Order new towel set",
    status: "done",
    priority: "medium",
    assignedTo: demoManagerEmail,
    createdBy: demoOwnerEmail,
    createdAt: subDays(now, 6).toISOString(),
    updatedAt: subDays(now, 3).toISOString(),
    completedAt: subDays(now, 3).toISOString(),
    shared: true,
    tags: ["inventory"],
  },
  {
    id: "demo-task-8",
    clientId,
    title: "Old: relaunch loyalty program (deferred)",
    description: "Parked for the next quarter — keeping the notes for context.",
    status: "archived",
    priority: "low",
    assignedTo: demoOwnerEmail,
    createdBy: demoOwnerEmail,
    createdAt: subDays(now, 40).toISOString(),
    updatedAt: subDays(now, 30).toISOString(),
    shared: true,
    tags: ["marketing"],
  },
];
